'use client'

import { useState, useEffect, useRef } from 'react'
import { format } from 'date-fns'
import {
  FileText,
  Download,
  QrCode,
  Copy,
  Check,
  Trash2,
  ChevronDown,
  ChevronUp,
  MapPin,
  Phone,
  Clock,
  AlertCircle,
  X,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Separator } from '@/components/ui/separator'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'
import type { MedicalReport } from '@/lib/types'
import QRCode from 'qrcode'

interface ReportViewerProps {
  reports: MedicalReport[]
  onDelete: (id: string) => void
  className?: string
}

function ReportCard({
  report,
  onDelete,
}: {
  report: MedicalReport
  onDelete: (id: string) => void
}) {
  const [isExpanded, setIsExpanded] = useState(false)
  const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null)
  const [isQrDialogOpen, setIsQrDialogOpen] = useState(false)
  const [copied, setCopied] = useState(false)
  const reportRef = useRef<HTMLDivElement>(null)

  const reportDate = new Date(report.createdAt)

  // Generate report text for export/sharing
  const generateReportText = () => {
    const lines = [
      '='.repeat(50),
      'MEDJOURNAL HEALTH REPORT',
      '='.repeat(50),
      '',
      `Generated: ${format(reportDate, 'MMMM d, yyyy h:mm a')}`,
      `Period: ${format(new Date(report.dateRange.start), 'MMM d, yyyy')} - ${format(new Date(report.dateRange.end), 'MMM d, yyyy')}`,
      '',
      '-'.repeat(50),
      'SUMMARY',
      '-'.repeat(50),
      report.summary,
      '',
    ]

    if (report.symptomPatterns.length > 0) {
      lines.push('-'.repeat(50))
      lines.push('OBSERVED PATTERNS')
      lines.push('-'.repeat(50))
      report.symptomPatterns.forEach((pattern, i) => {
        lines.push(`${i + 1}. ${pattern}`)
      })
      lines.push('')
    }

    if (report.symptomTimeline) {
      lines.push('-'.repeat(50))
      lines.push('SYMPTOM TIMELINE')
      lines.push('-'.repeat(50))
      lines.push(report.symptomTimeline)
      lines.push('')
    }

    lines.push('-'.repeat(50))
    lines.push('MOOD ANALYSIS')
    lines.push('-'.repeat(50))
    lines.push(report.moodTrends)
    lines.push('')

    if (report.recommendations.length > 0) {
      lines.push('-'.repeat(50))
      lines.push('WELLNESS SUGGESTIONS')
      lines.push('-'.repeat(50))
      report.recommendations.forEach((rec, i) => {
        lines.push(`${i + 1}. ${rec}`)
      })
      lines.push('')
    }

    if (report.suggestedSpecialists.length > 0) {
      lines.push('-'.repeat(50))
      lines.push('SUGGESTED SPECIALISTS')
      lines.push('-'.repeat(50))
      report.suggestedSpecialists.forEach((specialist) => {
        lines.push(`\n${specialist.name}`)
        lines.push(`  Specialty: ${specialist.specialty}`)
        lines.push(`  Address: ${specialist.address}`)
        lines.push(`  Phone: ${specialist.phone}`)
        if (specialist.availableHours) {
          lines.push(`  Hours: ${specialist.availableHours}`)
        }
      })
      lines.push('')
    }

    lines.push('='.repeat(50))
    lines.push('DISCLAIMER')
    lines.push('='.repeat(50))
    lines.push(report.disclaimer)
    lines.push('')
    lines.push('Generated by MedJournal - Your Personal Health Companion')

    return lines.join('\n')
  }

  // Generate QR code
  const generateQRCode = async () => {
    try {
      // Create a shortened version of the report for QR code
      const shortReport = {
        date: format(reportDate, 'yyyy-MM-dd'),
        summary: report.summary.substring(0, 200) + '...',
        patterns: report.symptomPatterns.slice(0, 3),
        mood: report.moodTrends.substring(0, 100),
      }
      
      const qrData = JSON.stringify(shortReport)
      const url = await QRCode.toDataURL(qrData, {
        width: 300,
        margin: 2,
        color: {
          dark: '#1a1a1a',
          light: '#ffffff',
        },
      })
      setQrCodeUrl(url)
    } catch (error) {
      console.error('Failed to generate QR code:', error)
      toast.error('Failed to generate QR code')
    }
  }

  useEffect(() => {
    if (isQrDialogOpen && !qrCodeUrl) {
      generateQRCode()
    }
  }, [isQrDialogOpen])

  // Export as text file
  const handleExport = () => {
    const text = generateReportText()
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `medjournal-report-${format(reportDate, 'yyyy-MM-dd')}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Report exported successfully')
  }

  // Copy to clipboard
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateReportText())
      setCopied(true)
      toast.success('Report copied to clipboard')
      setTimeout(() => setCopied(false), 2000)
    } catch (error) {
      toast.error('Failed to copy report')
    }
  }

  return (
    <Card className="overflow-hidden">
      <CardHeader className="pb-2">
        <div className="flex items-start justify-between gap-2">
          <div className="flex items-center gap-3">
            <div className="flex items-center justify-center size-10 rounded-lg bg-primary/10 text-primary">
              <FileText className="size-5" />
            </div>
            <div>
              <CardTitle className="text-base">
                Health Report
              </CardTitle>
              <CardDescription>
                {format(reportDate, 'MMM d, yyyy h:mm a')}
              </CardDescription>
            </div>
          </div>
          <div className="flex items-center gap-1">
            <Button
              variant="ghost"
              size="icon-sm"
              onClick={handleCopy}
              title="Copy report"
            >
              {copied ? (
                <Check className="size-4 text-green-600" />
              ) : (
                <Copy className="size-4" />
              )}
            </Button>
            <Button
              variant="ghost"
              size="icon-sm"
              onClick={handleExport}
              title="Export report"
            >
              <Download className="size-4" />
            </Button>
            <Dialog open={isQrDialogOpen} onOpenChange={setIsQrDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="ghost" size="icon-sm" title="Show QR code">
                  <QrCode className="size-4" />
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-md">
                <DialogHeader>
                  <DialogTitle>Report QR Code</DialogTitle>
                </DialogHeader>
                <div className="flex flex-col items-center gap-4 py-4">
                  {qrCodeUrl ? (
                    <>
                      <img
                        src={qrCodeUrl}
                        alt="Report QR Code"
                        className="rounded-lg border"
                      />
                      <p className="text-sm text-muted-foreground text-center">
                        Scan this QR code to view a summary of your health report.
                        Share with your healthcare provider for quick access.
                      </p>
                      <Button
                        variant="outline"
                        onClick={() => {
                          const a = document.createElement('a')
                          a.href = qrCodeUrl
                          a.download = `medjournal-qr-${format(reportDate, 'yyyy-MM-dd')}.png`
                          a.click()
                        }}
                        className="gap-2"
                      >
                        <Download className="size-4" />
                        Download QR Code
                      </Button>
                    </>
                  ) : (
                    <div className="animate-pulse bg-muted size-[300px] rounded-lg" />
                  )}
                </div>
              </DialogContent>
            </Dialog>
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  className="text-muted-foreground hover:text-destructive"
                  title="Delete report"
                >
                  <Trash2 className="size-4" />
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Delete this report?</AlertDialogTitle>
                  <AlertDialogDescription>
                    This action cannot be undone. This will permanently delete your
                    health report from {format(reportDate, 'MMM d, yyyy')}.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Cancel</AlertDialogCancel>
                  <AlertDialogAction
                    onClick={() => onDelete(report.id)}
                    className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                  >
                    Delete
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        </div>
      </CardHeader>
      <CardContent ref={reportRef}>
        <Badge variant="outline" className="mb-3">
          {format(new Date(report.dateRange.start), 'MMM d')} -{' '}
          {format(new Date(report.dateRange.end), 'MMM d, yyyy')}
        </Badge>

        {/* Summary preview */}
        <p className={cn(
          'text-sm text-muted-foreground mb-3',
          !isExpanded && 'line-clamp-3'
        )}>
          {report.summary}
        </p>

        {/* Expandable content */}
        {isExpanded && (
          <div className="flex flex-col gap-4 mt-4 pt-4 border-t">
            {/* Symptom Patterns */}
            {report.symptomPatterns.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold mb-2">Observed Patterns</h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  {report.symptomPatterns.map((pattern, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-primary mt-0.5">•</span>
                      {pattern}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Symptom Timeline */}
            {report.symptomTimeline && (
              <div>
                <h4 className="text-sm font-semibold mb-2 flex items-center gap-2">
                  <Clock className="size-4" />
                  Symptom Timeline
                </h4>
                <p className="text-sm text-muted-foreground">{report.symptomTimeline}</p>
              </div>
            )}

            {/* Mood Trends */}
            <div>
              <h4 className="text-sm font-semibold mb-2">Mood Analysis</h4>
              <p className="text-sm text-muted-foreground">{report.moodTrends}</p>
            </div>

            {/* Recommendations */}
            {report.recommendations.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold mb-2">Wellness Suggestions</h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  {report.recommendations.map((rec, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-primary mt-0.5">•</span>
                      {rec}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Specialists */}
            {report.suggestedSpecialists.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold mb-2">Suggested Specialists</h4>
                <div className="flex flex-col gap-2">
                  {report.suggestedSpecialists.map((specialist) => (
                    <div
                      key={specialist.id}
                      className="p-2 rounded-lg bg-muted/50 text-sm"
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-medium">{specialist.name}</span>
                        <Badge variant="secondary" className="text-xs">
                          {specialist.specialty}
                        </Badge>
                      </div>
                      <div className="flex items-center gap-1 text-xs text-muted-foreground mt-1">
                        <MapPin className="size-3" />
                        {specialist.address}
                      </div>
                      <div className="flex items-center gap-3 text-xs text-muted-foreground mt-1">
                        <span className="flex items-center gap-1">
                          <Phone className="size-3" />
                          {specialist.phone}
                        </span>
                        {specialist.availableHours && (
                          <span className="flex items-center gap-1">
                            <Clock className="size-3" />
                            {specialist.availableHours}
                          </span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Disclaimer */}
            <div className="p-3 rounded-lg bg-muted/50 text-xs text-muted-foreground flex items-start gap-2">
              <AlertCircle className="size-4 mt-0.5 shrink-0" />
              <p>{report.disclaimer}</p>
            </div>
          </div>
        )}

        {/* Expand/collapse button */}
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setIsExpanded(!isExpanded)}
          className="w-full mt-2 text-muted-foreground"
        >
          {isExpanded ? (
            <>
              <ChevronUp className="size-4 mr-1" />
              Show less
            </>
          ) : (
            <>
              <ChevronDown className="size-4 mr-1" />
              View full report
            </>
          )}
        </Button>
      </CardContent>
    </Card>
  )
}

export function ReportViewer({ reports, onDelete, className }: ReportViewerProps) {
  if (reports.length === 0) {
    return (
      <Card className={cn('flex flex-col items-center justify-center py-12', className)}>
        <FileText className="size-12 text-muted-foreground/50 mb-4" />
        <h3 className="text-lg font-medium text-foreground">No reports yet</h3>
        <p className="text-sm text-muted-foreground mt-1 text-center max-w-xs">
          Use the AI Assistant to generate your first health report from your journal entries.
        </p>
      </Card>
    )
  }

  return (
    <div className={cn('flex flex-col gap-4', className)}>
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold">Saved Reports</h2>
        <Badge variant="outline">{reports.length} reports</Badge>
      </div>
      <ScrollArea className="h-[calc(100vh-20rem)]">
        <div className="flex flex-col gap-4 pr-4">
          {reports.map((report) => (
            <ReportCard key={report.id} report={report} onDelete={onDelete} />
          ))}
        </div>
      </ScrollArea>
    </div>
  )
}
